server:
  port:8080
  
spring:
  datasource:
  	username:root
  	password:root
  	url:jdbc:mysql://localhost:3306/elemalldb-dit
  	driver-class-name:com.mysql.jdbc.Driver
  	
mybatis:
	mapper-locations:classpath:mapping/*Mapper.xml
	type-aliases-package:com.annguo.user.entity
#showSql
logging:
  level:
  	com:
  		annguo:
  			mapper : debug